import type {
  CampaignStatus,
  ClaimStatus,
  DealStatus,
  PayoutStatus,
  TransactionType,
} from '../../shared/types';

export const en = {
  brand: 'LocalLoop',
  demoMode: 'Demo mode',
  demoLauncherTitle: 'Local B2B rewards network',
  demoLauncherBody:
    'Pick a persona and walk the Magnolia × Camora demo from one shared server state.',
  openCustomer: 'Customer — Nino',
  openAdvertiser: 'Advertiser — Magnolia',
  openHost: 'Host — Camora',
  reset: 'Reset demo',
  loading: 'Loading…',
  errorGeneric: 'Something went wrong. Please try again.',
  emptyState: 'Nothing to show here yet.',
  workspaceAdvertiser: 'Advertiser workspace',
  workspaceHost: 'Host workspace',
  businessWorkspace: 'Business workspace',
  personaNino: 'Nino',
  personaMagnolia: 'Magnolia Film Lab',
  personaCamora: 'Camora',
  campaignName: 'Develop the Night',
  fundAction: 'Simulate campaign funding',
  verifyVisit: 'Verify Camora visit',
  redeemRequest: 'Request reward redemption',
  validateRedemption: 'Validate redemption',
  fundingLabel: 'Simulated budget',
  settlementLabel: 'Demo settlement on Solana devnet',
  capabilityMissing: 'This business does not have the requested capability.',
  revisionLabel: 'Revision',
  openExplorer: 'Open in Explorer',
  noReceipt: 'No transaction receipt yet.',
  connectWallet: 'Connect wallet',
  disconnectWallet: 'Disconnect',
  signAndFund: 'Sign authorization & simulate funding',
  walletConnected: 'Connected',
  walletUnsupported:
    'This wallet cannot sign messages. Connect a Wallet Standard wallet that supports signMessage.',
  challengePreview: 'Exact authorization message',
  fundingPending: 'Submitting funding proof on Solana devnet…',
  fundingSuccess: 'Campaign marked simulated-funded after confirmed proof.',
  fundingDisclosure:
    'No SOL leaves your connected wallet. You only sign a message. The server demo treasury records a memo on Solana devnet.',
  solanaNotReady:
    'Solana is not configured. Add DEMO_TREASURY_SECRET_KEY and DEMO_HOST_PUBLIC_KEY to .env, keep SOLANA_CLUSTER=devnet, fund the treasury via the faucet, then retry.',
  approveDeal: 'Approve deal',
  approveDealDisabled: 'Approve unlocks after simulated funding.',
  hostEmptyAdvertiser:
    'No advertiser campaigns for this business in the demo seed.',
  advertiserEmptyHost:
    'No host deals for this business in the demo seed. Switch to advertiser workspace for Magnolia’s campaign.',
  dealTerms: 'Deal terms',
  partnerDeals: 'Partner deals',
  budgetTotal: 'Total',
  budgetReserved: 'Reserved',
  budgetPaid: 'Paid',
  budgetRemaining: 'Remaining',
  rewardTerms: 'Reward',
  claimId: 'Claim ID',
  visitsProgress: 'Verified visits',
  payoutStatus: 'Payout',
  retryPayout: 'Retry payout',
  oneTimeUse: 'One-time reward — redeem once at Magnolia.',
  staffMode: 'Staff verification mode',
  qrPlacement: 'LocalLoop QR / pass placement (demo visual — no camera)',
  incomingRedemption: 'Incoming redemption',
  noRedemption: 'No redemption request yet.',
  mockedDeal: 'Mocked partner path',
  workingDeal: 'Live demo path',
  preview: {
    eyebrow: 'Interactive prototype · frontend only',
    title: 'One campaign. Three actors. One live story.',
    subtitle:
      'Walk the full Magnolia × Camora × Nino path — from funding to reward redemption.',
    mockDisclosure:
      'This is a fully mock prototype: wallet, signature, and devnet steps are simulated visually only.',
    guidedDemo: 'Guided demo',
    nextAction: 'Next action',
    switchToAction: 'Switch to the required view',
    forBusinesses: 'For businesses',
    businessSignIn: {
      eyebrow: 'Business access · mock',
      title: 'Sign in to LocalLoop',
      subtitle:
        'Manage campaigns, host partnerships, and reward redemptions from one workspace.',
      emailLabel: 'Work email',
      emailPlaceholder: 'you@magnoliafilmlab.com',
      passwordLabel: 'Password',
      passwordPlaceholder: '••••••••',
      submit: 'Sign in',
      submitting: 'Signing in…',
      back: 'Back to demo',
      mockNote:
        'Mock sign-in only — no account is created and nothing is sent to a server.',
      signedInEyebrow: 'Welcome back',
      signedInTitle: 'What would you like to do?',
      signedInSubtitle: 'Pick a path to continue the Magnolia demo workspace.',
      createCampaign: 'Create campaign',
      viewCampaigns: 'View campaigns',
    },
    createCampaign: {
      eyebrow: 'New campaign · mock',
      title: 'Create a campaign',
      subtitle:
        'Describe the perk, set the host deal, connect a wallet, then deposit a simulated SOL budget.',
      back: 'Back',
      sectionOffer: 'What you offer',
      sectionDeal: 'Host deal',
      sectionBudget: 'Wallet & budget',
      campaignName: 'Campaign name',
      campaignNamePlaceholder: 'Develop the Night',
      perks: 'Perks',
      perksPlaceholder: '10 ₾ off film development and scanning',
      features: 'Features & conditions',
      featuresPlaceholder: 'Applies to orders over 40 ₾ at Magnolia Film Lab',
      hostPartner: 'Host partner',
      hostPartnerPlaceholder: 'Camora',
      visitRequirement: 'Visit requirement',
      visitRequirementPlaceholder: '3 verified visits at the host',
      dealTerms: 'Deal terms',
      dealTermsPlaceholder: '0.005 SOL paid to the host per redemption · max 10',
      budgetAmount: 'Campaign budget (SOL)',
      walletLabel: 'Advertiser wallet',
      walletDisconnected: 'Not connected',
      walletConnected: '7Fka…Loop · mock connection',
      connectWallet: 'Connect wallet',
      walletReady: 'Wallet connected',
      depositBudget: 'Deposit SOL to campaign budget',
      depositing: 'Depositing…',
      depositDone: 'Budget deposited',
      walletRequired: 'Connect a wallet before depositing.',
      formRequired: 'Fill in every field to continue.',
      fundingDisclosure:
        'Mock deposit only — no SOL leaves the connected wallet. Budget is simulated; on-chain proof stays a demo memo.',
      successTitle: 'Campaign ready',
      successBody:
        'Your perk, deal, and simulated SOL budget are set. Continue into the advertiser workspace.',
      openWorkspace: 'Open advertiser workspace',
    },
    reset: 'Restart prototype',
    campaign: 'Campaign',
    campaignStory:
      'Magnolia rewards loyal Camora guests with a film development discount.',
    simulatedBudget: 'Simulated budget',
    remainingBudget: 'Remaining budget',
    reservedBudget: 'Reserved',
    paidBudget: 'Paid',
    partnerNetwork: 'Partner network',
    proposedMock: 'Mock offer',
    canonicalDeal: 'Main demo path',
    fullJourney: 'Full journey',
    advertiserTab: 'Magnolia · Advertiser',
    hostTab: 'Camora · Host',
    customerTab: 'Nino · Customer',
    advertiserKicker: 'Campaign management',
    advertiserTitle: 'Magnolia Film Lab',
    advertiserBody:
      'Simulate funding for the campaign and confirm Nino’s reward redemption.',
    wallet: 'Wallet',
    walletDisconnected: 'Not connected',
    walletConnected: '7Fka…Loop · mock connection',
    connectWallet: 'Connect mock wallet',
    signFunding: 'Sign authorization',
    authorizationDone: 'Authorization complete',
    signDisclosure: 'Free message signature — no SOL leaves the wallet.',
    validate: 'Confirm redemption',
    completePayout: 'Complete mock payout',
    hostKicker: 'Staff mode',
    hostTitle: 'Camora',
    hostBody: 'Approve the partnership and verify Nino’s remaining visits.',
    approveDeal: 'Approve offer',
    offerApproved: 'Offer approved',
    waitingForFunding: 'Waiting for Magnolia’s simulated funding first',
    verifyVisit: 'Verify visit',
    allVisitsVerified: 'All three visits verified',
    passTitle: 'Nino’s LocalLoop pass',
    passHint: 'QR visual · camera is not used in this prototype',
    customerKicker: 'Reward pass',
    customerTitle: 'Hi, Nino',
    customerBody: 'Three verified visits at Camora unlock Magnolia’s reward.',
    progress: 'Visit progress',
    reward: 'Your reward',
    rewardTitle: '10 ₾ discount',
    rewardBody:
      'On film development and scanning over 40 ₾ at Magnolia Film Lab.',
    camoraRequirement: '3 verified visits at Camora',
    camoraRewardShort: '10 ₾ off film development and scanning',
    perRedemption: '0.005 SOL / redemption',
    maxRedemptions: 'Max 10',
    hostDealMeta: 'Magnolia Film Lab · 0.005 SOL per redemption',
    requestReward: 'Request reward redemption',
    redemptionRequested: 'Redemption requested',
    lockedReward: 'One more step and the reward unlocks.',
    unlockedReward: 'Reward is ready to redeem.',
    history: 'Live activity',
    sharedStory: 'One story across every view',
    emptyHistory: 'Actions will show up here.',
    receipt: 'Mock devnet receipt',
    receiptReference: 'Prototype reference',
    receiptMemo: 'Memo',
    noExplorer:
      'No Explorer link on purpose — this record is not a blockchain transaction.',
    fundingProof: 'Mock funding proof',
    payoutProof: 'Mock payout proof',
    successTitle: 'Full LocalLoop closed',
    successBody:
      'Nino got the reward, Camora got a 0.005 SOL mock payout, Magnolia kept 0.045 SOL.',
    statusReady: 'Ready',
    statusWaiting: 'Waiting on the previous step',
    visitVerified: 'Verified',
    visitPending: 'Pending',
    tsreRequirement: '2 verified visits at TSRE Gym',
    tsreReward: 'Future partner offer',
    stepCount: '/ 7 steps',
    journey: {
      connectWallet: 'Mock wallet connect',
      authorizeFunding: 'Funding authorization',
      camoraApproval: 'Camora approval',
      ninoVisits: 'Nino visits 3/3',
      requestReward: 'Reward request',
      magnoliaConfirm: 'Magnolia confirmation',
      mockPayout: 'Mock payout',
    },
    historySeed: 'Nino’s first visit is already verified — 1/3',
    historyConnect: 'Mock wallet connected',
    historyFund: 'Simulated funding authorized',
    historyApprove: 'Camora approved the offer',
    historyVisit: (n: number) => `Camora verified a visit — ${n}/3`,
    historyRequest: 'Nino requested reward redemption',
    historyValidate: 'Magnolia confirmed the redemption',
    historyPayout: 'Camora mock payout completed',
    nextConnect: 'Connect Magnolia’s mock wallet',
    nextSign: 'Sign the simulated funding authorization',
    nextApprove: 'Approve the offer as Camora',
    nextVisit: (n: number) => `Verify Nino’s visit ${n}/3`,
    nextRequest: 'Request the reward as Nino',
    nextValidate: 'Confirm redemption as Magnolia',
    nextPayout: 'Finish the mock devnet settlement',
    nextDone: 'Demo complete — start over',
  },
} as const;

export const claimStatusLabel: Record<ClaimStatus, string> = {
  locked: 'Locked',
  unlocked: 'Unlocked',
  redemption_requested: 'Redemption requested',
  redeemed: 'Redeemed',
};

export const payoutStatusLabel: Record<PayoutStatus, string> = {
  not_ready: 'Not ready',
  pending: 'Pending',
  processing: 'Processing',
  paid: 'Paid',
  failed: 'Failed',
};

export const campaignStatusLabel: Record<CampaignStatus, string> = {
  draft: 'Draft',
  simulated_funded: 'Simulated funded',
  live: 'Live',
  completed: 'Completed',
};

export const dealStatusLabel: Record<DealStatus, string> = {
  proposed: 'Proposed',
  active: 'Active',
  completed: 'Completed',
};

export const transactionTypeLabel: Record<TransactionType, string> = {
  funding_proof: 'Funding proof',
  host_payout: 'Host payout',
};
