import type {
  CampaignStatus,
  ClaimStatus,
  DealStatus,
  PayoutStatus,
  TransactionType,
} from '../../shared/types';

export const en = {
  brand: 'LocalLoop',
  demoMode: 'Demo mode',
  demoLauncherTitle: 'Local B2B rewards network',
  demoLauncherBody:
    'Pick a persona and walk the Magnolia × Camora demo from one shared server state.',
  openCustomer: 'Customer — Nino',
  openAdvertiser: 'Advertiser — Magnolia',
  openHost: 'Host — Camora',
  reset: 'Reset demo',
  loading: 'Loading…',
  errorGeneric: 'Something went wrong. Please try again.',
  emptyState: 'Nothing to show here yet.',
  workspaceAdvertiser: 'Advertiser workspace',
  workspaceHost: 'Host workspace',
  businessWorkspace: 'Business workspace',
  personaNino: 'Nino',
  personaMagnolia: 'Magnolia Film Lab',
  personaCamora: 'Camora',
  campaignName: 'Develop the Night',
  fundAction: 'Simulate campaign funding',
  verifyVisit: 'Verify Camora visit',
  redeemRequest: 'Request reward redemption',
  validateRedemption: 'Validate redemption',
  fundingLabel: 'Simulated budget',
  settlementLabel: 'Demo settlement on Solana devnet',
  capabilityMissing: 'This business does not have the requested capability.',
  revisionLabel: 'Revision',
  openExplorer: 'Open in Explorer',
  noReceipt: 'No transaction receipt yet.',
  connectWallet: 'Connect wallet',
  disconnectWallet: 'Disconnect',
  signAndFund: 'Sign authorization & simulate funding',
  walletConnected: 'Connected',
  walletUnsupported:
    'This wallet cannot sign messages. Connect a Wallet Standard wallet that supports signMessage.',
  phantomNotDetected:
    'Phantom is not available in this browser. Open this page in the browser where the Phantom extension is installed and unlocked, then try again.',
  walletConnectionTimedOut:
    'Phantom did not finish connecting. Unlock the extension, approve the connection, and try again.',
  challengePreview: 'Exact authorization message',
  fundingPending: 'Submitting funding proof on Solana devnet…',
  fundingSuccess: 'Campaign marked simulated-funded after confirmed proof.',
  fundingDisclosure:
    'No SOL leaves your connected wallet. You only sign a message. The server demo treasury records a memo on Solana devnet.',
  solanaNotReady:
    'Solana is not configured. Add DEMO_TREASURY_SECRET_KEY and DEMO_HOST_PUBLIC_KEY to .env, keep SOLANA_CLUSTER=devnet, fund the treasury via the faucet, then retry.',
  approveDeal: 'Approve deal',
  approveDealDisabled: 'Approve unlocks after simulated funding.',
  hostEmptyAdvertiser:
    'No advertiser campaigns for this business in the demo seed.',
  advertiserEmptyHost:
    'No host deals for this business in the demo seed. Switch to advertiser workspace for Magnolia’s campaign.',
  dealTerms: 'Deal terms',
  partnerDeals: 'Partner deals',
  budgetTotal: 'Total',
  budgetReserved: 'Reserved',
  budgetPaid: 'Paid',
  budgetRemaining: 'Remaining',
  rewardTerms: 'Reward',
  claimId: 'Claim ID',
  visitsProgress: 'Verified visits',
  payoutStatus: 'Payout',
  retryPayout: 'Retry payout',
  oneTimeUse: 'One-time reward — redeem once at Magnolia.',
  staffMode: 'Staff verification mode',
  qrPlacement: 'LocalLoop QR / pass placement (demo visual — no camera)',
  incomingRedemption: 'Incoming redemption',
  noRedemption: 'No redemption request yet.',
  mockedDeal: 'Mocked partner path',
  workingDeal: 'Live demo path',
  continue: 'Continue',
  useReward: 'Use reward at Magnolia',
  declineReward: 'Don’t use this reward',
  waitingOnHost: 'Waiting for Camora to verify your visits.',
  waitingOnFunding: 'Waiting for Magnolia to simulate campaign funding.',
  waitingOnCustomer: 'Waiting for Nino to use or decline the reward.',
  waitingOnApproval: 'Waiting for Camora to approve the deal.',
  waitingOnRedemption: 'Waiting for Nino to request redemption at Magnolia.',
  budgetUnchanged: 'Campaign budget unchanged — no host payout.',
  declinedDone:
    'You kept the visits at Camora but did not use the Magnolia reward. No payout will be sent.',
  redemptionSent: 'Redemption requested. Magnolia will validate next.',
  wizard: {
    advertiser: {
      campaignTitle: 'Campaign',
      campaignHeadline: 'Develop the Night',
      campaignBody:
        'Magnolia runs a 0.05 SOL simulated budget to reward Camora guests with film-lab discounts.',
      fundTitle: 'Fund on Solana',
      fundHeadline: 'Authorize simulated funding',
      fundBody:
        'Sign a message only. The server treasury posts a real memo on Solana devnet.',
      hostsTitle: 'Hosts',
      hostsHeadline: 'Camora is your live host path',
      hostsBody:
        'One working deal with Camora. TSRE Gym stays a proposed mock partner.',
      redemptionTitle: 'Redemption',
      redemptionHeadline: 'Validate Nino’s reward',
      redemptionBody:
        'When Nino asks to use the discount at Magnolia, confirm it here.',
      redemptionWaitingHeadline: 'Waiting for redemption',
      redemptionWaitingBody:
        'Nino unlocks the reward after three Camora visits, then chooses to use or decline it.',
      redemptionDeclinedHeadline: 'Reward declined',
      redemptionDeclinedBody:
        'Nino did not use the Magnolia reward. Simulated budget stays at 0.05 SOL.',
      settleTitle: 'Settlement',
      settlePaidHeadline: 'Host payout confirmed',
      settlePaidBody:
        'Server treasury sent 0.005 SOL to Camora on Solana devnet.',
      settleDeclinedHeadline: 'No payout',
      settleDeclinedBody:
        'Because the reward was not used, advertiser budget did not change.',
    },
    host: {
      dealTitle: 'Incoming deal',
      dealHeadline: 'Magnolia wants Camora as host',
      dealBody:
        '3 verified visits unlock a Magnolia film reward. Host payout is 0.005 SOL on success.',
      visitsTitle: 'Verify visits',
      visitsHeadline: 'Staff verification',
      visitsBody: 'Confirm each qualifying Camora visit for Nino.',
      earningsTitle: 'Earnings',
      earningsWaitingHeadline: 'Waiting on customer',
      earningsWaitingBody:
        'After the reward unlocks, Nino chooses to use it at Magnolia or decline.',
      earningsPaidHeadline: 'Paid on Solana devnet',
      earningsPaidBody: '0.005 SOL arrived from the server demo treasury.',
      earningsDeclinedHeadline: 'No payout this time',
      earningsDeclinedBody:
        'Nino still visited Camora — you earned the foot traffic, but no campaign payout.',
    },
    customer: {
      dealTitle: 'Your deal',
      dealHeadline: 'Camora × Magnolia',
      dealBody:
        'Complete three verified visits at Camora to unlock 10 ₾ off film development at Magnolia.',
      progressTitle: 'Progress',
      progressHeadline: 'Visit Camora',
      progressBody: 'Camora staff verify each visit. You’re already at 1 of 3.',
      unlockedTitle: 'Reward unlocked',
      unlockedHeadline: 'Ready at Magnolia',
      unlockedBody:
        'Your one-time reward is unlocked. Use it at Magnolia or leave it.',
      chooseTitle: 'Choose',
      chooseHeadline: 'Use the reward?',
      chooseBody:
        'Using it lets Magnolia validate and pays Camora 0.005 SOL. Declining leaves the budget unchanged.',
      doneTitle: 'Done',
      doneUsedHeadline: 'Redemption in progress',
      doneUsedBody: 'Magnolia will validate your request next.',
      doneRedeemedHeadline: 'Reward redeemed',
      doneRedeemedBody: 'Thanks — Camora’s payout can settle on Solana devnet.',
      doneDeclinedHeadline: 'Reward not used',
      doneDeclinedBody:
        'No Magnolia purchase and no host payout. Your Camora visits still happened.',
    },
  },
  preview: {
    eyebrow: 'Interactive prototype frontend only',
    title: 'One campaign. Three actors. One live story.',
    subtitle:
      'Walk the full Magnolia × Camora × Nino path — from funding to reward redemption.',
    mockDisclosure:
      'This is a fully mock prototype: wallet, signature, and devnet steps are simulated visually only.',
    guidedDemo: 'Guided demo',
    nextAction: 'Next action',
    switchToAction: 'Switch to the required view',
    forBusinesses: 'For businesses',
    forCustomers: 'Browse offers',
    businessSignIn: {
      authLabel: 'Business authentication',
      signInTab: 'Sign in',
      signUpTab: 'Sign up',
      eyebrow: 'Business access mock',
      title: 'Sign in to LocalLoop',
      subtitle:
        'Manage campaigns, host partnerships, and reward redemptions from one workspace.',
      signUpEyebrow: 'Create business account mock',
      signUpTitle: 'Join LocalLoop',
      signUpSubtitle:
        'Set up a mock business account, then create or review campaigns.',
      businessNameLabel: 'Business name',
      businessNamePlaceholder: 'Your business name',
      emailLabel: 'Work email',
      emailPlaceholder: 'you@magnoliafilmlab.com',
      passwordLabel: 'Password',
      passwordPlaceholder: '••••••••',
      submit: 'Sign in',
      submitting: 'Signing in…',
      signUpSubmit: 'Sign up',
      signingUp: 'Creating account…',
      back: 'Back to demo',
      mockNote:
        'Mock sign-in — use the prefilled Magnolia details to open its profile.',
      signUpMockNote:
        'Mock sign-up only — the account stays in this browser and nothing is sent to a server.',
      signedInEyebrow: 'Welcome back',
      signedInTitle: 'What would you like to do?',
      signedInSubtitle:
        'Create a campaign as an advertiser, or review host campaigns sent to Camora.',
      createCampaign: 'Create campaign',
      viewCampaigns: 'View campaigns',
    },
    createCampaign: {
      eyebrow: 'New campaign mock',
      title: 'Create a campaign',
      subtitle:
        'Describe the perk, set the host deal, connect a wallet, then deposit a simulated SOL budget.',
      back: 'Back',
      sectionOffer: 'What you offer',
      sectionDeal: 'Deal',
      sectionBudget: 'Wallet & budget',
      campaignName: 'Campaign name',
      campaignNamePlaceholder: 'Develop the Night',
      perks: 'Perks',
      perksPlaceholder: '10 ₾ off film development and scanning',
      features: 'Features & conditions',
      featuresPlaceholder: 'Applies to orders over 40 ₾ at Magnolia Film Lab',
      addDesiredPartner: 'Add a desired partner',
      removePartner: 'Remove partner',
      hostPartner: 'Host partner',
      hostPartnerPlaceholder: 'Camora',
      partnerSearch: 'Search partners',
      partnerSearchPlaceholder: 'Search for a partner…',
      partnerNoResults: 'No partners match that search.',
      partnerSelected: 'Selected partner',
      requirements: 'Requirements',
      requirementsPlaceholder: '3 verified visits at the host',
      dealTerms: 'Deal',
      dealTermsPlaceholder: '0.005 SOL paid to the host per redemption max 10',
      budgetAmount: 'Campaign budget (SOL)',
      walletLabel: 'Advertiser wallet',
      walletDisconnected: 'Not connected',
      walletConnected: '7Fka…Loop mock connection',
      connectWallet: 'Connect wallet',
      walletReady: 'Wallet connected',
      depositBudget: 'Deposit SOL to campaign budget',
      depositing: 'Depositing…',
      depositDone: 'Budget deposited',
      walletRequired: 'Connect a wallet before depositing.',
      formRequired: 'Fill in every field to continue.',
      fundingDisclosure:
        'Mock deposit only — no SOL leaves the connected wallet. Budget is simulated; on-chain proof stays a demo memo.',
      successTitle: 'Campaign ready',
      successBody:
        'Your perk, deal, and simulated SOL budget are set. Continue to My Campaigns.',
      openWorkspace: 'Open advertiser workspace',
      viewMyCampaigns: 'My Campaigns',
      myCampaigns: {
        eyebrow: 'Advertiser mock',
        title: 'My Campaigns',
        subtitle: 'Campaigns saved in this browser from the create flow.',
        empty: 'No campaigns yet. Create one to see it here.',
        createNew: 'Create campaign',
        back: 'Back',
        budget: 'Budget',
        partner: 'Partner',
        noPartner: 'No partner',
        deal: 'Deal',
      },
      previewLabel: 'Campaign preview',
      previewEmpty: 'Fill in the fields to preview your campaign.',
      previewSaved: 'Saved to this browser',
      previewPartner: 'Desired partner',
      previewNoPartner: 'No partner selected yet',
      previewBudget: 'Budget',
      logoLabel: 'Campaign logo',
      logoUpload: 'Upload logo',
      logoChange: 'Change logo',
      logoRemove: 'Remove',
      logoHint: 'PNG, JPG, or SVG stays in this browser only',
    },
    advertiserProfile: {
      eyebrow: 'Business workspace',
      title: 'Magnolia Film Lab',
      subtitle: 'Manage campaigns, redemptions, payouts, and business details.',
      back: 'Sign out',
      createCampaign: 'Create campaign',
      deleteCampaign: 'Delete campaign',
      deleteCampaignConfirm: (campaignName: string) =>
        `Delete “${campaignName}” from this browser?`,
      tabsLabel: 'Advertiser profile sections',
      tabs: {
        overview: 'Overview',
        campaigns: 'My Campaigns',
        redemptions: 'Redemptions',
        profile: 'Profile',
      },
      stats: {
        campaigns: 'Campaigns',
        totalBudget: 'Simulated budget',
        pendingRedemptions: 'Pending redemptions',
        paidOut: 'Paid out',
      },
      overview: {
        nextTitle: 'Workspace summary',
        manageTitle: 'Your campaigns are ready to manage',
        manageBody:
          'Review partner deals, simulated budgets, and incoming redemption requests.',
        emptyTitle: 'Create your first campaign',
        emptyBody:
          'Define a perk, add an optional partner, and set a simulated SOL budget.',
        liveCampaignTitle: 'Live demo campaign',
        liveCampaignBody:
          'This is Magnolia’s guided-demo campaign management — wallet, budget, partners, and redemptions.',
      },
      openFromDemo: {
        title: 'Magnolia lives in the business profile',
        body: 'Campaign management, wallet funding, and partner deals now open inside Magnolia’s advertiser profile.',
        action: 'Open Magnolia profile',
      },
      status: {
        simulatedFunded: 'Simulated funded',
      },
      redemptions: {
        title: 'Redemptions',
        subtitle: 'Review customer requests and host payout progress.',
        emptyTitle: 'No redemption requests',
        emptyBody:
          'New customer requests will appear here for validation before a host payout.',
      },
      profile: {
        title: 'Business profile',
        subtitle: 'Identity and workspace access for this business.',
        businessName: 'Business name',
        email: 'Work email',
        capabilities: 'Capabilities',
        capabilityValue: 'Advertiser Host',
        wallet: 'Wallet',
        walletConnected: '7Fka…Loop mock connection',
        walletDisconnected: 'Not connected',
        mockNote:
          'Profile and wallet state are local mock data for this prototype.',
      },
    },
    customerOffers: {
      eyebrow: 'Customer offers',
      title: 'Nearby rewards',
      subtitle:
        'Partnership perks from local advertisers and host businesses.',
      back: 'Back to demo',
      backToOffers: 'Back to offers',
      empty: 'No partnership offers yet. When advertisers add a host partner, offers show up here.',
      partnership: 'Partnership',
      perk: 'Perk',
      requirements: 'Requirements',
      deal: 'Deal',
      seededLabel: 'Live demo',
      savedLabel: 'New',
      fakeLabel: 'Nearby',
      openPass: 'Open my pass',
      openOffer: 'Open offer',
      hostAt: 'At',
      detailEyebrow: 'Your reward pass',
      detailTitle: (advertiserName: string) => `${advertiserName} reward`,
      detailBody:
        'Collect host visits, unlock the perk, then request redemption.',
      simulateVisit: (hostPartner: string) => `Log visit at ${hostPartner}`,
      allVisitsDone: 'All visits logged',
      visitHint:
        'For the live Magnolia × Camora path, Camora staff verify visits in the host workspace. Other offers include a mock visit button here.',
    },
    hostCampaigns: {
      eyebrow: 'Host workspace',
      title: 'Campaigns at Camora',
      subtitle:
        'Review partnership requests sent to you, then manage every campaign you host.',
      back: 'Back to demo',
      backToList: 'Back to campaigns',
      tabsLabel: 'Host campaign sections',
      tabs: {
        incoming: 'Sent to you',
        hosting: 'Hosting now',
      },
      incomingTitle: 'Sent to you',
      incomingSubtitle: 'Advertisers asking Camora to host their perk.',
      incomingEmpty: 'No new partnership requests right now.',
      hostingTitle: 'Hosting now',
      hostingSubtitle: 'Approved campaigns where Camora verifies visits.',
      hostingEmpty: 'Approve a request to start hosting.',
      openCampaign: 'Open campaign',
      fromAdvertiser: 'From',
      proposedLabel: 'Needs approval',
      activeLabel: 'Hosting',
      seededLabel: 'Live demo',
      savedLabel: 'New',
      fakeLabel: 'Nearby',
      detailEyebrow: 'Host console',
      detailBody:
        'Approve the partnership, then verify customer visits on this campaign.',
      waitingForFunding: 'Waiting for the advertiser’s simulated funding first',
    },
    reset: 'Restart prototype',
    campaign: 'Campaign',
    campaignStory:
      'Magnolia rewards loyal Camora guests with a film development discount.',
    simulatedBudget: 'Simulated budget',
    remainingBudget: 'Remaining budget',
    reservedBudget: 'Reserved',
    paidBudget: 'Paid',
    partnerNetwork: 'Partner network',
    proposedMock: 'Proposed mock',
    canonicalDeal: 'Main demo path',
    fullJourney: 'Full journey',
    advertiserTab: 'Magnolia Advertiser',
    hostTab: 'Camora Host',
    customerTab: 'Nino Customer',
    advertiserKicker: 'Campaign management',
    advertiserTitle: 'Magnolia Film Lab',
    advertiserBody:
      'Simulate funding for the campaign and confirm Nino’s reward redemption.',
    wallet: 'Wallet',
    walletDisconnected: 'Not connected',
    walletConnected: '7Fka…Loop mock connection',
    connectWallet: 'Connect mock wallet',
    signFunding: 'Sign authorization',
    authorizationDone: 'Authorization complete',
    signDisclosure: 'Free message signature — no SOL leaves the wallet.',
    validate: 'Confirm redemption',
    completePayout: 'Complete mock payout',
    hostKicker: 'Staff mode',
    hostTitle: 'Camora',
    hostBody: 'Approve the partnership and verify Nino’s remaining visits.',
    approveDeal: 'Approve offer',
    offerApproved: 'Offer approved',
    waitingForFunding: 'Waiting for Magnolia’s simulated funding first',
    verifyVisit: 'Verify visit',
    allVisitsVerified: 'All three visits verified',
    passTitle: 'Nino’s LocalLoop pass',
    passHint: 'QR visual camera is not used in this prototype',
    customerKicker: 'Reward pass',
    customerTitle: 'Hi, Nino',
    customerBody: 'Three verified visits at Camora unlock Magnolia’s reward.',
    progress: 'Visit progress',
    reward: 'Your reward',
    rewardTitle: '10 ₾ discount',
    rewardBody:
      'On film development and scanning over 40 ₾ at Magnolia Film Lab.',
    camoraRequirement: '3 verified visits at Camora',
    camoraRewardShort: '10 ₾ off film development and scanning',
    perRedemption: '0.005 SOL / redemption',
    maxRedemptions: 'Max 10',
    hostDealMeta: 'Magnolia Film Lab 0.005 SOL per redemption',
    requestReward: 'Request reward redemption',
    redemptionRequested: 'Redemption requested',
    lockedReward: 'One more step and the reward unlocks.',
    unlockedReward: 'Reward is ready to redeem.',
    history: 'Live activity',
    sharedStory: 'One story across every view',
    emptyHistory: 'Actions will show up here.',
    receipt: 'Mock devnet receipt',
    receiptReference: 'Prototype reference',
    receiptMemo: 'Memo',
    noExplorer:
      'No Explorer link on purpose — this record is not a blockchain transaction.',
    fundingProof: 'Mock funding proof',
    payoutProof: 'Mock payout proof',
    successTitle: 'Full LocalLoop closed',
    successBody:
      'Nino got the reward, Camora got a 0.005 SOL mock payout, Magnolia kept 0.045 SOL.',
    statusReady: 'Ready',
    statusWaiting: 'Waiting on the previous step',
    visitVerified: 'Verified',
    visitPending: 'Pending',
    tsreRequirement: '2 verified visits at TSRE Gym',
    tsreReward: 'Future partner offer',
    stepCount: '/ 7 steps',
    journey: {
      connectWallet: 'Mock wallet connect',
      authorizeFunding: 'Funding authorization',
      camoraApproval: 'Camora approval',
      ninoVisits: 'Nino visits 3/3',
      requestReward: 'Reward request',
      magnoliaConfirm: 'Magnolia confirmation',
      mockPayout: 'Mock payout',
    },
    historySeed: 'Nino’s first visit is already verified — 1/3',
    historyConnect: 'Mock wallet connected',
    historyFund: 'Simulated funding authorized',
    historyApprove: 'Camora approved the offer',
    historyVisit: (n: number) => `Camora verified a visit — ${n}/3`,
    historyRequest: 'Nino requested reward redemption',
    historyValidate: 'Magnolia confirmed the redemption',
    historyPayout: 'Camora mock payout completed',
    nextConnect: 'Connect Magnolia’s mock wallet',
    nextSign: 'Sign the simulated funding authorization',
    nextApprove: 'Approve the offer as Camora',
    nextVisit: (n: number) => `Verify Nino’s visit ${n}/3`,
    nextRequest: 'Request the reward as Nino',
    nextValidate: 'Confirm redemption as Magnolia',
    nextPayout: 'Finish the mock devnet settlement',
    nextDone: 'Demo complete — start over',
  },
} as const;

export const claimStatusLabel: Record<ClaimStatus, string> = {
  locked: 'Locked',
  unlocked: 'Unlocked',
  redemption_requested: 'Redemption requested',
  redeemed: 'Redeemed',
  declined: 'Declined',
};

export const payoutStatusLabel: Record<PayoutStatus, string> = {
  not_ready: 'Not ready',
  pending: 'Pending',
  processing: 'Processing',
  paid: 'Paid',
  failed: 'Failed',
};

export const campaignStatusLabel: Record<CampaignStatus, string> = {
  draft: 'Draft',
  simulated_funded: 'Simulated funded',
  live: 'Live',
  completed: 'Completed',
};

export const dealStatusLabel: Record<DealStatus, string> = {
  proposed: 'Proposed',
  active: 'Active',
  completed: 'Completed',
};

export const transactionTypeLabel: Record<TransactionType, string> = {
  funding_proof: 'Funding proof',
  host_payout: 'Host payout',
};
